### ISSUE TITLE
Invoke-MTBuild > "Failed to create Manifest" after update from 0.0.6 to 0.0.8

### ISSUE THREAD

**Issue by tohaase** [belibug/ModuleTools#7]
After updating from 0.0.6 to 0.0.8 and executing "Invoke-MTBuild" this error comes:

`Write-Error: Failed to create Manifest: Cannot validate argument on parameter 'Tags'. The argument is null, empty, or an element of the argument collection contains a null value. Supply a collection that does not contain any null values and then try the command again.`

Uninstalling 0.0.8 and installing 0.0.6 makes it working again. 😄 

This is my project file:
```
{
  "ProjectName": "Example",
  "Description": "Description",
  "Version": "0.0.1",
  "Manifest": {
    "Author": "Author",
    "PowerShellHostVersion": "1.0",
    "GUID": "3944b711-ac04-4823-ba37-1ca2eeab6f4d",
    "Tags": [],
    "ProjecUri": ""
  }
}
```

**Comment by tohaase** [comment]
Same with the GitHub-action:

```
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install ModuleTools from PSGallery
        run: Install-PSResource -Repository PSGallery -Name ModuleTools -TrustRepository
        shell: pwsh

      - name: Build Module
        run: Set-Location -Path ./Test; Invoke-MTBuild -Verbose
        shell: pwsh

      - name: List files
        run: Get-ChildItem ./Test/dist -Recurse
        shell: pwsh

```
